### ISSUE TITLE
[Ch01] Clean Code

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/cleancode-study#1]

**Comment by jjangsungwon** [comment]
`좋은 프로그래머는 어떤 사람일까?` 에 대한 고민을 끝없이 반복하고 있다. 최근에 개발뿐만 아니라, 다양한 영역에서 기초가 중요하다는 글을 자주 접하게 되었고 회사에서 프로젝트를 진행하면서도 많이 깨닫고 있다. 따라서, 이번 클린 코드 책 스터디는 나에게 아주 긍정적인 경험과 자극이 될 것 같다.

1장의 주된 내용은 `클린 코드가 무엇일까?` 였다. 개인적으로 클린 코드를 정의해 보자면 `읽기 쉬운 코드`라고 생각한다. 읽기 쉬우면 설명하기도 쉽고 유지 보수하기도 쉽다고 생각하기 때문이다. 하지만, 책에서는 나의 생각과 비슷한 부분도 있었지만 다른 부분도 있었다. 다른 점은 바로 읽기 쉬운 코드와 고치기 쉬운 코드는 엄연히 다르다는 부분이었다. 사실, 아직은 이해가 안 된다. 읽기 쉬우면 고치기 쉽지 않을까? 하지만, 아직 책의 초반이고 뒷부분을 읽고 나면 나의 생각은 바뀌어있을 수도 있다. 이렇게 책의 내용과 나의 생각 그리고 스터디 팀원들의 생각들을 알아가고 이야기하는 시간을 통해 많이 성장할 수 있을 것이라 기대한다.

추가적으로 기억에 남은 구문
- 반드시 필요한 내용만 담아야 한다. 코드를 읽는 사람에게 프로그래머가 단호하다는 인상을 줘야 한다.
- 테스트 케이스가 없는 코드는 깨끗한 코드가 아니다.
- 프로그램을 단순하게 보이도록 만드는 열쇠는 언어가 아니라 프로그래머다.
- 이 책이 그저 “기분 좋은 책”으로 머물지 않기를 바란다.

**Comment by ChanhuiSeok** [comment]
1장에는 클린 코드에 대한 많은 사람들의 의견이 정리되어 있었다. 그 중에서 론 제프리스가 말한 부분(중복을 피하라. 한 기능만 수행하라.)을 기억하고 싶다. 지금까지 코드를 작성했던 기억을 되살려볼 때, 함수가 정말 하나의 기능만 수행하는지? 그리고 중복된 부분이 있는지 등을 확실히 파악하고 넘어갔는가 물어본다면 조금 자신이 없을 것 같다.
그리고 함수명을 애매하게 지어서 어떤 역할인지 한눈에 보이지 않았던 적이 있다. 뒷 챕터에서도 나오겠지만 코드는 최대한 단순하게, 이해하기 쉽고 읽기 좋게 작성해야 한다.
클린코드에 있는 내용을 100% 따라한다기 보다는 책 내용을 참고해서 나의 코드 작성 기준을 잘 만들어 나가고 싶다.
