### ISSUE TITLE
[Ch13] Concurrency

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/cleancode-study#13]

**Comment by jjangsungwon** [comment]
### 느낀 점
- 11, 12장이 비교적 어려워서 13장은 쉽게 느껴졌다. 공용 데이터 소싱 프로젝트에서 동시성, 데드락과 관련된 설계를 진행하였는데 책에 있는 내용과 유사한 점들이 많았다.

**동시성이 필요한 경우**
- 무엇과 언제를 분리하는 전략이다. 무엇과 언제를 분리하면 애플리케이션의 구조와 효율이 극적으로 나아진다.
- **응답 시간과 작업 처리량 개선이라는 요구사항으로 인해 직접적인 동시성 구현이 불가피하다.**

**동시성은 항상 성능을 높여준다 ?**
- 여러 프로세스가 동시에 처리할 독립적인 계산이 충분히 많은 경우에만 성능이 높아진다.

**모델 예시**
- 생산자 - 소비자
  - 책에서 말한 생산자 -소비자와 유사한 카프카를 사용하고 있다. (카프카는 시그널을 보내지 않는 점이 다르다)
- 읽기 - 쓰기
  - 양쪽 균형을 잡으면서 동시 갱신 문제를 피하는 해법이 필요하다.
  - db 격리 레벨 결정 및 db table 설계할 때 항상 고려하는 부분
- 식사하는 철학자들
  - 해결 방법이 다양한 것으로 알고 있음.

**올바른 종료 코드는 구현하기 어렵다.**
- 모든 스레드가 정상 종료 혹은 비정상 종료되었는지 확인하는 역할을 수행하는 tasks 를 만들어서 종료 상태를 파악하고 있다.

**스레드 코드 테스트하기**
- 다시 돌렸더니 통과하더라는 이유로 그냥 넘어가면 절대로 안 된다.
- 일회성 문제를 계속 무시한다면 잘못된 코드 위에 코드가 계속 쌓인다.
- 스레드 개수를 조율하기 쉽게 코드를 구현한다.
  - 스레드를 생성하기 전에 스레드 개수를 조율하는 tasks를 만들어서 수행하고 있다. 프로그램 처리율과 효율에 따라 스스로 스레드 개수를 조율하고 있다.
  - 실행할 때 환경에 따라 설정을 바꿔줄 방법도 필요하다. -> 실행할 때 환경에 따라 읽는 설정 파일을 다르게 하여 구현하고 있다.
  - 아주 소수만 실패하기 때문에 스레드 코드는 오류를 찾기가 쉽지 않다. -> 베타 버전으로 서비스를 출시하여 사용자들이 사용하면서 겪는 버그를 수집하고 해결하고 있다.

**Comment by hhhyunwoo** [comment]
동시성과 깔끔한 코드는 양립하기 어렵다! 

멀티스레드 코드는 시스템이 부하를 받기 전까지는 멀쩡하게 돌아가지만, 소수의 케이스에서 이슈가 발생함

- 두개의 스레드 기준으로 잠재적인 경로는 최대 12870개
    - long일 경우 2704156

멀티스레드 프로그래밍에서 어떻게 하면 코드를 깨끗하고 효율적으로 짤 수 있는가에 대한 내용 

## 동시성

- 디커플링 전략
    - 무엇과 언제를 분리
    - 구조적 개선
        - 각 스레드는 다른 스레드와 무관하게 돌아감
- 응답 시간과 작업 처리량 개선
- 항상 성능을 높여주는 것은 아님
- 설계 변할 수 있음
- 동시성에 대해 이해해야함
- 복잡함
- 버그 재현 어려움
- 설계 전략을 근본적으로 다시 바라봐야함

## 동시성 방어원칙

- SRP
    - 반복적으로 나오는 중요한 포인트
    - 동시성과 관련없는 코드는 분리해야함
- Critical section
    - 일반적으로 synchronized로 보호함
    - 최대한 줄여라
- 스레드 테스트 코드
    - 재현 매우 어려움
    - 일회성 오류를 그냥 넘기면 안됨
    - 일단 멀티 스레드랑 관련없는 외부 코드부터 잘 돌아야 함!
    - 다양한 설정에서 돌려봐야함
        - 보조코드
            - 실패하는 경로가 실행될 확률이 극도로 저조함
            - jiggle(흔들다)
            - 무작위로 nop, sleep 이나 yield를 수행
            - 서비스 환경에 바로 넣을 수는 없기 때문에 같은 이름의 두개의 메서드를 생성

→ 이전에 나온 내용대로 코드를 잘 분리하고 잘 짜고, 동시성에 대해 잘 이해하고 있으면 됨!!


### Golang 예제
```go
package main

import (
	"fmt"
	"time"
)

func sendHello(ch1 chan string) {
	time.Sleep(time.Second * 1)
	ch1 <- "hello"
}

func sendWorld(ch2 chan string) {
	time.Sleep(time.Second * 3)
	ch2 <- " world"
}

func receive(ch1 chan string, ch2 chan string, done chan string) {
	var msg string
	for {
		select {
		case msg1 := <-ch1:
			fmt.Println("msg: ", msg1)
			msg += msg1

		case msg2 := <-ch2:
			fmt.Println("msg: ", msg2)
			msg += msg2
			done <- msg
			return
		default:
			fmt.Println("default는 계속 호출됩니다.")
			time.Sleep(time.Second)
		}
	}
}

func main() {
	ch1 := make(chan string)
	ch2 := make(chan string)
	done := make(chan string)
	go sendHello(ch1)
	go sendWorld(ch2)
	go receive(ch1, ch2, done)
	result := <-done
	fmt.Println("result: ", result)
}
===
output

default는 계속 호출됩니다.
default는 계속 호출됩니다.
msg:  hello
default는 계속 호출됩니다.
msg:   world
result:  hello world
```

**Comment by ChanhuiSeok** [comment]
## 13장 동시성

- 동시성은 `무엇과 언제를 분리하는 전략`이다. (결합을 없애는 전략)
- 무엇과 언제를 분리하면 애플리케이션 구조와 효율이 극적으로 나아진다.
- 구조적 개선만을 위해 동시성을 채택하는건 아니고 응답 시간과 작업 처리량 개선을 위해 직접적인 동시성 구현이 불가피하다.(다중 스레드)

- 동시성은 어렵다. 미신과 오해가 많다.
    - 항상 성능을 높여준다? → 항상이 아니라 때로 높여준다고 할 수 있다. 대기 시간이 아주 길어 여러 스레드가 프로세서를 공유할 수 있거나 여러 프로세서가 동시에 처리할 독립적인 계산이 충분히 많은 경우에만 성능이 높아진다.
    - 동시성을 구현해도, 설계는 변하지 않는다. → 아니다. 단일 스레드와 다중 스레드 시스템은 설계가 다르다.
    - 동시성은 다소 부하를 유발할 수 있다. 코드도 더 짜야 한다.
    - 동시성은 간단한 문제여도 복잡하다.
    - 동시성 버그는 일반적으로 재현하기 어렵다.
    - 동시성 구현을 하려면 근본적인 설계 전략을 재고해야 한다.
    
    (참고) 자바스크립트는 싱글 스레드 방식으로 동작하지만, 이벤트 루프를 통해 동시성을 제공한다.
    
- 동시성 방어 원칙
    - 난관 파트에서 동시성이 일으킬 수 있는 문제 코드에 대해 살펴봤다. 이런 문제로부터 시스템을 방어하는 원칙과 기술들을 소개하고 있다.
    - 단일 책임 원칙 : 동시성 관련 코드는 다른 코드와 분리해야 한다.
    - 자료 범위 제한 : 공유 객체를 사용하는 **임계 영역**을 synchronized 키워드로 보호해야 한다.
    - 자료 사본 이용 : 공유 자료를 줄이려면 처음부터 공유하지 않는 방법이 좋다. 각 스레드가 객체를 복사해 사용하여 읽기 전용으로 사용하거나, 한 스레드가 해당 사본에서 결과를 가져오는 방법이 가능하다. 공유 객체를 피하는 방법이 있으면, 문제를 일으킬 가능성이 아주 낮다.
    - 스레드는 가능한 독립적으로 구현하자.
    
- 라이브러리 이해

- 실행 모델 이해. 운영체제 데드락에서 배웠던 용어들이 나와서 조금 친숙했다.
    - 한정된 자원, 상호 배제, 기아, 데드락, 라이브락 / 라이브락은 락을 거는 단계에서 각 스레드가 서로를 방해하는 것이다. 스레드는 계속해서 진행하려 하지만 공명(확인 필요)으로 인해 굉장히 오랫동한 혹은 여원히 진행하지 못한다.
    - (1) 생산자-소비자 모델 : 생산자 스레드와 소비자 스레드. 생산자 스레드가 정보 생성 후 버퍼나 대기열에 넣으면 소비자 스레드가 대기열에서 정보를 가져와 사용하며, 대기열은 한정된 자원이다. 문제는 동시에 서로에게서 시그널을 기다릴 가능성이 있다.
    - (2) 읽기-쓰기 : 읽기-쓰기 방식에서는 기아 현상을 막으면서도 처리율이 떨어지는 문제도 같이 잡아야 한다.
    - (3) 식사하는 철학자들 : 이것도 예전에 배웠던 개념이다. 왼쪽 혹은 오른쪽 철학자가 포크를 사용중이면 다 먹을 때까지 기다리는 문제다.
    
- 동기화하는 메서드 사이에 존재하는 의존성을 이해하자. 공유 객체 하나에는 메서드 하나만 사용하자.
- 동기화하는 부분을 작게 만들어라.
- 올바른 종료 코드는 구현하기 어렵다.
- 스레도 코드 테스트하기. 여기서도 결국 충분한 테스트를 진행하자는게 주 목표일 것 같다.
  - 다중 스레드를 쓰는 코드 부분을 다양한 환경에 쉽게 끼워 넣을 수 있게 스레드 코드를 구현하라
  - 다중 스레드를 쓰는 코드 부분을 상황에 맞게 조율할 수 있게 작성하라.
