### ISSUE TITLE
[Ch14] Successive Refinement

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/cleancode-study#14]

**Comment by jjangsungwon** [comment]
## 느낀점
14장은 확장성이 부족했던 Args 코드를 점진적으로 개선하는 모습을 보여준다. 정말 좋은 말과 내용이 많았지만 자바를 사용하지 않는 나에게는 개선 내용이 피부로 크게 와닿지는 않았다. 대표적인 이유는 아래 2가지다.
- 자바에 대한 지식이 부족함
- 파이썬은 argparse 기능 제공함 (책에서 보여준 예시를 2줄로 구현 가능)
  - 직접 구현해본 경험이 있었다면 파이썬 언어를 사용하는 사람들에게도 와닿는 내용이 많았을 것이라 생각함

### 프로그래밍은 과학보다 공예에 가깝다
- 깨끗한 코드를 짜려면 먼저 지저분한 코드를 짠 뒤에 정리해야 한다.
- 작문할 때 초안부터 작성한다. 1차 초안을 쓰고, 그 초안을 고쳐 2차 초안을 만들고, 게속 고쳐 최종안을 만들라고 한다.
- 깔끔한 작품을 내놓으려면 단계적으로 개선해야 한다.

### 테스트 주도 개발 (Test Driven Development)
- 프로그램을 망치는 가장 좋은 방법 중 하나는 개선이라는 이름 아래 구조를 크게 뒤집는 행위이다.
- 어떤 프로그램은 그저 그런 `개선`에서 결코 회복하지 못한다.
- `개선` 전과 똑같이 프로그램을 돌리기가 아주 어렵기 때문이다.
- 따라서 저자는 테스트 주도 개발 기법을 사용하였다.
- TDD는 언제 어느 때라도 시스템이 돌아가야 한다는 원칙을 따른다. 즉, TDD는 시스템을 망가뜨리는 변경을 허용하지 않는다. 변경을 가한 후에도 시스템이 변경 전과 똑같이 돌아가야 한다는 말이다.

### 분할
- 소프트웨어 설계는 분할만 잘해도 품질이 크게 높아진다.
- 적절한 장소를 만들어 코드만 분리해도 설계가 좋아진다.
- 관심사를 분리하면 코드를 이해하고 보수하기 훨씬 쉬워진다.

### 돌아가는 코드만으로는 부족하다.
- 단순히 돌아가는 코드에 만족하는 프로그래머는 전문가 정신이 부족하다.
- 나쁜 코드보다 더 오랫동안 더 심각하게 개발 프로젝트에 악영향을 미치는 요인도 없다.
- 오래된 의존성을 찾아내 깨려면 상당한 시간과 인내심이 필요하다.
- 코드는 언제나 최대한 깔끔하고 단순하게 정리하자. 절대로 썩어가게 방치하면 안 된다.

## 기타
- 자바는 장황한 언어이다.

**Comment by hhhyunwoo** [comment]
클린 코드를 위한 리펙터링 작업을 아주 상세하게 보여준 장

내가 코드를 짜고 있는 방식에 대해서 다시 한번 돌아보게 됨. 단순히 돌아가는 코드를 짜고 있었던 것은 아닌지?

클린 코드를 위한 리펙터링은 내가 해왔던, 내가 생각하는 리펙터링 보다 훨씬 어렵고 투자해야하는 시간이 많이 필요함. 

나쁜 일정, 나쁜 요구사항, 나쁜 팀 역학은 복구가 가능. 하지만 나쁜 코드는 썩어 문드러짐. 점점 무게가 늘어난다. 

### 인상깊었던 부분

계속해서 코드를 구현하다가 저자는 어느 순간 계속 밀어붙이면 엄청난 스노우볼이 생길 것을 예상. 

이렇게 할 수 있으려면 TDD가 무조건 필요함. 개선이라는 이름 아래 구조를 크게 뒤짚는 행위는 프로그램을 망치는 가장 좋은 방법임. 이렇게 하면 똑같이 돌리는 것이 아주 어려움. 

TDD를 사용하면 언제든지 코드는 돌아감. 변경 후에도 변경 전과 동일하게 돌아간다.

**Comment by ChanhuiSeok** [comment]
### 14장 점진적인 개선

일단 처음에 잘 짜여진 코드를 보여주고, 처음부터 저렇게 구현하지 않았다는 점을 강조하고 있다.
✏️ 깨끗하고 우아한 프로그램은 한 방에 뚝딱 내놓을 수 없고, 프로그래밍은 과학보다는 공예에 가깝다는 사실을 기억하자.
**깨끗한 코드를 짜려면, 먼저 지저분한 코드를 짠 뒤에 정리해야 한다.** (1차 초안 → 2차 초안 → 최종안을 만드는 느낌으로!)

무조건 돌아가는 프로그램을 목표로 잡고, 일단 프로그램이 돌아가면 다음 업무로 넘어가는 경우가 있는데 이런 행동은 전문가로서 자살 행위라는 사실을 기억하자.

**점진적으로 개선하다**
개선이라는 이름 아래 구조를 크게 뒤집는 행위는 프로그램을 쉽게 망칠 수 있는 방법이다. 그래서 `테스트 주도 개발`이라는 기법을 사용한다. TDD는 시스템을 망가뜨리는 변경을 허용하지 않기 때문에, 변경을 가한 후에도 시스템이 변경 전과 똑같이 돌아가야 한다는 말이다.
✏️ 이 때에도 `테스트 코드가 중요하다는 사실`을 한번 더 되새길 수 있었다. 책에서 점진적으로 개선해 나가는 와중에도, 테스트 코드가 있었기 때문에 변경하는 과정에서 제대로 동작하는지 확인이 가능했다.

**결론**
그저 돌아가는 코드만으로는 부족하다. 단순히 돌아가는 코드에 만족하는 프로그래머는 전문가 정신이 부족하다.
✏️ 설계와 구조를 개선할 시간이 없다고 변명하지 말자! 

나쁜 코드를 깨끗한 코드로 개선하기보다는, 처음부터 코드를 깨끗하게 유지하도록 하자. 코드는 언제나 최대한 깔끔하고 단순하게 정리하자.
✏️ 14장 초입에서, 깨끗한 코드를 짜려면 먼저 지저분한 코드를 짠 뒤에 정리하자고 했었다. 그러니까, 지저분한 코드 상태로 그대로 두지 말고, 일단 그렇게 짠 다음 바로 정리해 나가자는 말로 이해하면 될 것 같다.
