### ISSUE TITLE
[Ch15] JUnit Internals

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/cleancode-study#15]

**Comment by hhhyunwoo** [comment]
제목만 보았을 때는 Junit 사용을 통한 테스트 방법? 이런 내용이 나올 줄 알았는데, 

전혀 아니었고 내부 코드 구현에 대한 이야기였다.

Junit 이 잘 짜여진 코드이라는 것을 알게되었고, 그런 잘 짜여진 코드에도 보이스카웃 규칙을 적용해서 더 깨끗하게 만들 수 있다는게 신기했다.

코드는 역시 계속해서 수정이 필요한 것인가 보다.

코드 커버리지가 100%라는 것도 놀랐다. 

최근 우리 팀도 테스트 코드를 작성하고 있는데 코드 커버리지 100% 를 목표로 하고있다. 그게 얼마나 어려운 일인지 알기에 놀랐다! 

### 인상깊었던 점

- 조건문 캡슐화
    - 나열하기 보다 가독성이 좋게 캡슐화를 하자
    - 부정문 보단 긍정문이 읽기 좋다.
- 반환 방식에 대한 함수 리팩터링
    - 변수 반환하는 함수가 있을 수 있고, 그렇지 않은 함수가 있을 수 있다.
    - 일관성을 유지하자
- builder 패턴
    - 생성 패턴 중 하나
        - 생성 패턴 : 인스턴스를 만드는 절차를 추상화 하는 패턴
    - 팩토리 패턴, 팩토리 메서드 패턴 같은 경우 클래스의 속성값이 많아지면
        - → 필요없는 값에 대해서 일일이 null 넘겨줘야함 / 복잡
        - ![image](https://user-images.githubusercontent.com/37402136/191996758-ba88875a-3e28-46d9-82b5-b4afd17d5b6c.png)

**Comment by jjangsungwon** [comment]
JUnit 을 잘 모르고 사용할 일이 없을 것 같아 이번 챕터는 읽을 필요가 있을까? 라는 생각을 하였다. 하지만, 도입부부터 흥미를 이끄는 일화가 있었고 기억에 남는 말도 많아서 유익한 파트였다.
- `비좁은 기내에서 엔지니어 둘이 랩탑을 꺼내 코드를 짜는 일 밖에 다른 무엇을 하겠는가?`

### **코드 커버리지 100%**
- 코드 커버리지 100%가 나왔다는 말은 처음 봤다. 컴퓨터를 전공하는 사람들은 100%라는 말을 거의 사용하지 않는다. 추측성 말을 많이 사용한다. (ex, ~ 것 같다.) 100%라는 말은 쉽게 할 수 없기 때문에 나조차도 쉽게 확신을 하지 않는다. 그렇기에 코드 커버리지 100%는 정말로 존경스럽다.

### **조건문 캡슐화**
- 조건문을 메서드로 만들면 코드도 간결해지고 의도를 명확하게 표현할 수 있다.
- 부정문보다 긍정문이 이해하기 쉽다.

### **일관적인 함수 사용 방식**
- 반환값이 있는 함수, 반환값이 없는 함수가 compactExpectedAndActual() 함수 내부에 존재하였다. 저자는 이를 보고 함수 사용방식이 일관적이지 못하다고 판단하였다.
- 하지만, 반환값이 필요없는데 굳이 반환할 필요가 있을까라는 생각을 한다. (저자가 마지막에 정리한 코드를 보면 다시 반환값이 없는 형태로 돌아갔다)

### 기타
- prefixIndex가 필요한 이유가 분명히 드러나지 않아서 다른 방식으로 리팩터링한 것이 기억에 남는다.
- JUnit 처럼 유명한 프레임워크는 이미 완벽하게 리팩터링이 되어있을 것이라 생각하였다. 하지만, `완벽한 리팩터링`은 존재하지 않는다. 역시 코드는 계속해서 관리해야한다는 점을 다시 깨닫게 되었다.

**Comment by ChanhuiSeok** [comment]
## 15장

자바 프레임워크 중에서 가장 유명한 JUnit 코드를 평가하면서 배우는 장이었다. (JUnit의 개발 시작을 비행기 안에서 했다는게 흥미로웠다)

아래 차례대로, 코드를 조금 더 개선해보고 있다.

- 변수 이름에 범위를 명시할 필요가 없으므로, 접두어를 제거한다.
- 캡슐화되지 않은 조건문을 캡슐화하자. if문 안에 여러 조건이 or(and) 형태로 쭉 나열되는 것보다, **조건문을 메서드로 뽑아내서 적절한 이름을 붙인다.**
- **부정문은 긍정문보다 이해가기 약간 더 어렵다.** if문에 들어간 것을 긍정으로 만든다. ✏️ 이 부분이 공감이 갔다. 예전에 코드 개선 당시 조건 변수가 부정형으로 되어 있어서 이해하기 어려웠고 **(부정형에 또 부정하는 형태가 나옴)** , 그래서 긍정형으로 바꾼 적이 있다.
- **함수 사용방식을 일관적으로 만들자.** ✏️ 책의 예시에서는, 함수 안에서 마지막 두 줄은 변수를 반환하지만 그 위의 줄은 반환값이 없는 형태였고 이를 모두 통일시키는 작업으로 개선했다. (그런데 최종본으로 제시한 findCommonPrefixAndSuffix() 함수에선 다시 반환값이 없는 형태로 만들었다..?)
- **각 함수들의 사용 순서를 충분하게 고려하는 방식**으로 개선하고 있다. (어떤 함수가 잘못된 순서로 먼저 호출되어 버그가 발생하는 일이 없도록)

깨끗한 코드로 가는 길은 무엇일까? 에 대한 것을 느낄 수 있는 15장이었다. 수많은 시행착오를 반복하는 작업..
