### ISSUE TITLE
[Ch16] Refactoring SerialDate

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/cleancode-study#16]

**Comment by hhhyunwoo** [comment]
책의 저자가 어떤식으로 리펙터링을 진행하는지 아주 상세하게 간접경험을 할 수 있었다.

저자는 자바 JCommon의 SerialDate라는 클래스를 보이스카웃 정신에 따라 처음부터 끝까지 리팩터링을 진행하였다. 

### 인상깊었던 점

- 먼저 테스트 코드를 손봐서 코드 커버리지를 최대한 올린 다음에 진행한다.
    - 코드가 제대로 돌아야 리펙터링이 의미가 있다.
- 이렇게 까지 해야하나 라는 생각도 조금은 들었음… ㅎ

**Comment by jjangsungwon** [comment]
책 초반에 SerialDate를 구현한 데이비드 길버트에 대한 이야기가 나온다. 이전 파트 JUnit을 만든 켄트 벡, 에릭 감마에 대한 설명과 달리 데이비드 길버트는 왜 이렇게 우수한 프로그래머라고 강조할까? 생각하였다. 그 이유는 책을 읽으면서 점점 알 수 있었다. (사실상 SerialDate 전반적인 코드에 대한 비판을 하기 위한 발판..?) 하지만, 코드에 대한 비판은 나에 대한 비판이 아니다!

### **첫째, 돌려보자**
- 리팩터링을 하기 위해서 테스트 커버리지를 확인한다. 
- 리팩터링을 하기 위해서는 높은 테스트 커버리지가 필요하기 때문에 추후 리팩터링을 하기 위해서라도 테스트 코드 커버리지를 신경 써서 구현해야 한다.

### **둘째, 고쳐보자**
- 코드를 고칠 때마다 단위 테스트를 실행한다.
- 의미 없는 주석은 모두 제거한다.
- 한 소스 코드에 여러 언어를 사용하지 말자.
- 부모 클래스는 자식을 몰라야 한다.
- 이름! 이름! 이름이 정말 중요하다. 클린 코드는 이름과 테스트 코드가 핵심이라고 생각한다.
- 너무 사소해 테스트할 필요가 없는 코드도 존재한다.

+) 리팩터링을 하는 과정을 상세하게 알려주는 파트였지만 반대로 상세하게 이해하기는 힘들었다. 저자가 코드를 바꾼 의도, 원본 코드, 바뀐 코드 3가지를 함께 봐야하는데 책 안에서 3가지를 함께 보기 힘들었다.

**Comment by ChanhuiSeok** [comment]
## 16장

JCommon 라이브러리의 SerialDate라는 클래스를 살펴보는 16장이다. 그리고, 개선점에 대해 살펴본다.

**돌려보자**

- SerialDateTest라는 클래스는 돌려보면 실패하는 케이스는 없었지만, 50% 정도만 커버하고 있었다. 더 높은 커버리지를 위해 책에서는 단위 테스트를 독자적으로 구현하는 방식으로 개선하고 있다. ✏️ 1차적으로 코드를 돌려보면서 오류가 없는지 확인하는 작업이었다.

**고쳐보자**

돌려보자 파트에서 코드를 고쳐보고 모든 테스트 케이스를 통과시켰으니 이제는 코드를 올바르게 고쳐본다.

- 법적인 정보는 필요, 변경 이력은 60년대에 나온 방식이므로 없앤다.
- Javadoc 주석에 네 가지 언어(자바, 영어, Javadoc, HTML)가 혼재되어 있으니 주석 전부를 `<pre>` 로 감싸는 식으로 맞춘다.
- 클래스 이름에 대한 추상화 수준을 고민하고, 적절하게 바꾸자. (SerialDate → DayDate)
- 불필요한 주석은 삭제하자.
- 중복이 존재하는 메서드를 분리해낸다.
- 논리적 의존성 vs 물리적 의존성에 대한 이야기가 나온다. 변수보다는 함수를 통해 데이터를 공유하는 방식이 적절하다는 의미라고 한다. 이 부분은 좀 더 살펴봐야 겠다.
