### ISSUE TITLE
[Ch17] Smells and Heuristics

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/cleancode-study#17]

**Comment by ChanhuiSeok** [comment]
## 17장 냄새와 휴리스틱

역시 17장이라 그런가 마무리 느낌이 많이 났다.
제목이 왜 **냄새**와 휴리스틱일까 했는데 ‘코드 냄새’라는 의미였다. 나쁜 코드의 냄새를 정리했다고 한다.
항목이 정말 많지만 그 중에서 좀 더 와닿은 것 위주로 정리하고, 그 중에서도 중요하다고 생각되는 부분에 볼드처리를 했다.

주석

- **쓸모 없는 주석은 달지 말자.**
- **코드만으로 충분한데 구구절절 설명하는 주석을 달지 말자. 성의없이 달지 말자.**
- **주석으로 처리된 코드를 내버려 두지 말자.**

환경

- 빌드와 테스트는 간단하게 한 단계(하나의 명령어)로 끝나야 한다.

함수

- 너무 많은 인수를 쓰지 말자.
- 출력 인수를 쓰지 말자. (보통 코드를 볼 때 인수는 입력값으로 간주함)
- **함수 플래그 인수(boolean)는 여러 기능을 수행한다는 명백한 증거다. 혼란을 초래한다.**
- **아무도 호출하지 않는 죽은 코드는 바로 삭제하자.**

일반

- 당연한 동작을 구현하지 않는다. - 최소 놀람의 원칙을 지킨다. 코드를 보는 사람을 놀라게 해서는 안 된다는 의미이다. 의미 전달을 잘 해야 한다는 것으로 이해했다.
- 모든 경계 조건을 찾고, 테스트하는 테스트 케이스를 작성하자.
- **중복 제거. 코드에서 중복을 없애는 건 굉장히 중요하다. DRY(Don’t Repeat Yourself) 원칙이라고도 한다.**
- 죽은 코드를 제거하라.
    - 불가능한 조건을 확인하는 ifans, throw문이 없는 try문에서의 catch 블록, 아무도 호출하지 않는 유틸함수, switch/case에서 불가능한 case 조건 등
- 변수와 함수는 사용되는 위치에 가깝게 정의하고, 지역 변수는 처음으로 사용하기 직전에 사용한다.
- **일관성 있는 코드를 작성하자. 유사한 개념에 각기 다른 단어를 사용하면 코드를 읽기 어려울 것이다.**
- 인수를 넘겨 동작을 선택하는 대신, 새로운 함수로 분리하면 좋다.
- 변수 이름은 서술적인 변수 이름을 사용하자. 의미 없는 변수이름을 쓰지 말자.
- **기능이 뻔히 보일 정도로 함수를 깔끔하고 명확하게 재구성하자.**
- 한 모듈이 다른 모듈에 의존할 때, 물리적 의존성도 있어야 한다.
- 매직 숫자는 일반적으로 코드에 숫자를 사용하지 말라는 규칙이다. 명명된 상수로 바꾸는 것이 좋다. 단, 상수가 너무 이해하기 쉽고 코드 자체가 자명하다면 굳이 상수로 바꿀 필요는 없다.
- **조건을 캡슐화해라. 부울 논리는 조건의 의도를 분명히 밝히는 함수로 표현하자.**
- 여러 추상화 수준이 뒤섞이지 않게 분리를 잘 하자.

이름

- **서술적인 이름을 사용하자.**
- 적절한 추상화 수준에서 이름을 선택하자.
- 가능하다면 표준 명명법을 사용하자. (예: 데코레이터 패턴을 활용한다면 Decorator 단어 사용 등)
- 이름으로 부수 효과도 설명을 하자.

테스트

- **테스트 케이스는 잠재적으로 깨질 만한 모든 부분을 테스트해야 한다. ‘이 정도면 충분하지 않을까?’ 라는 척도를 사용하지 말자.**
- 경계 조건을 테스트하자.
- 버그 주변은 철저히 테스트하자.
- 실패 패턴을 살펴보자. - 때로는 테스트 케이스가 실패하는 패턴으로 문제를 진단할 수 있다.
- **테스트는 빨라야 한다. 최대한 테스트 케이스가 빨리 돌아가게 노력한다.**

**Comment by hhhyunwoo** [comment]
# Ch17. **Smells and Heuristics**

코드에서 나는 나쁜 냄새? 나쁜 습관들에 대한 리스트!

클린코드에서 이야기했던 고쳐야하는 부분들을 적어둬서 나중에 참고해도 괜찮을 듯 하다.

## 인상깊었던 부분

### 주석

- 꼭 필요한 부분만 주석으로 남기자. 남긴다면 단어들을 신중하게 선택해서 최대한 멋지게 남기자 (당연한 소리 반복 X, 주절대지 않고 간결하고 명료하게)
- 주석으로 처리된 코드는 즉각 지우자! 어짜피 git이 관리해줌

### 함수

- 인수개수는 최대한 줄이자. 없다면 가장 좋다.
- 플래그 인수는 함수가 여러 기능을 한다는 증거임. 피해야한다
- 호출하지 않는 함수는 삭제하자.
    - 테스트 커버리지 검사로 확인 가능

### 환경
- make file 


### 일반

- 중복을 발견할 때마다 추상화할 기회로 간주해라
    - switch, if 문은 다형성으로 대체할 수 있는 기회임
        - 다형성 객체를 생성해서 switch 문을 대신할 수 있음
- 서술적인 변수 사용을 통해서 프로그램 가독성을 높이자.
    - 이름은 소프트웨어 가독성의 90%를 결정한다. 이름이 매우 중요하기 때문에 신중하게 고르고 선택한 이름이 적합한지 자주 되돌아 보자
    - 긴 범위는 긴 이름을 사용하자
- 매직숫자는 명명된 숫자로 바꾸자! (근데 합리적인 숫자들은 괜찮! )
- 조건문 캡슐화 및 긍정문으로 바꾸기
- 함수의 리턴 값을 통해서 시간적인 결합 만들기

### 유비쿼터스 언어

- DDD 에서 나오는 단어
    - 특정 프로젝트에 적용할 표준을 고안한 것
    - 단순히 명사 뿐만 아니라 동사까지 용어 사전으로 관리 해야함
    - ![image](https://user-images.githubusercontent.com/37402136/193506615-51429018-3a7e-4dba-b4f1-1626d8bf2eea.png)
    

### 테스트

- 커버리지 도구 사용
- 
![image](https://user-images.githubusercontent.com/37402136/193506593-f6f63995-4ea1-4d3a-ab5e-e395207de573.png)

**Comment by jjangsungwon** [comment]
저자가 프로그램을 수정할 때마다 겪은 나쁜 냄새를 정리한 파트이다. 앞으로 개발하면서 나쁜 냄새를 겪을 때마다 정리하여 저자가 만든 노트를 업데이트할 계획이다.

#### 주석
- 꼭 필요한 내용만 주석으로 남기자. 주석은 빨리 낡는다.

#### 함수
- 함수에서 인수 개수는 작을수록 좋다.
- 일반적으로 독자는 인수를 입력으로 간주한다.
- boolean 인수는 함수가 여러 기능을 수행한다는 명백한 증거다. 혼란을 초래하므로 피해야 마땅하다.

#### 일반
- 최소 놀람의 원칙에 의거해 함수나 클래스는 다른 프로그래머가 당연하게 여길 만한 동작과 기능을 제공해야 한다.
  - 최소 놀람의 원칙: 필요한 기능에 깜짝 놀랠만한 요소가 있다면 해당 기능을 다시 설계할 필요가 있을 수 있다.
- 코드에서 중복을 발견할 때마다 추상화할 기회로 간주하라.
- 최근 15년 동안 나온 디자인 패턴은 대다수가 중복을 제거하는 잘 알려진 방법에 불과하다.
- 변수와 함수는 사용되는 위치에 가깝게 정의한다. 지역 변수는 처음으로 사용하기 직전에 선언하며 수직으로 가까운 곳에 위치해야 한다.
- 매직 숫자는 명명된 상수로 교체하자. 매직 숫자는 의미가 분명하지 않은 토큰도 포함한다.
- 조건을 캡슐화하자. 부울 논리는 조건의 의도를 분명히 밝히는 함수로 정의하는 것이 이해하기 좋다.
- 부정 조건은 긍정 조건보다 이해하기 어렵다.
- 함수는 한 가지만 해야 한다.
- 시간적인 결합을 위해 연결 소자를 사용할 수 있다.

#### 이름
- 소프트웨어 가독성의 90%는 이름이 결정한다.
- 신중하게 선택한 이름은 추가 설명을 포함한 코드보다 강력하다.
- 코드 범위가 길수록 이름을 정확하고 길게 짓는다.

#### 테스트
- 테스트 케이스가 확인하지 않는 조건이나 검증하지 않는 계산이 있다면 그 테스트는 불완전하다.
- 커버리지 도구는 테스트가 빠뜨리는 공백을 알려준다.
- 버그 주변은 철저히 테스트하라.

휴리스틱 목록을 익힌다고 소프트웨어 장인이 되지는 못한다. 전문가 정신과 장인 정신은 가치에서 나온다. 그 가치에 기반한 규율과 절제가 필요하다.
