### ISSUE TITLE
[Ch03] Functions

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/cleancode-study#3]

**Comment by jjangsungwon** [comment]
[느낀 점]

다른 사람의 코드를 읽다 보면 술술 읽히는 코드가 있고, 한 줄 한 줄이 읽기 어려운 코드가 있다. 후자의 경우가 더 많은 것 같다. 이는 대부분 함수가 길고 하나의 함수에서 하고자 하는 일이 많기 때문이라고 생각한다. 이런 나의 생각을 읽은 듯이 책에서도 함수를 만들 때 중요한 점 중 '작게', '한 가지'가 포함되어 있었다.

한 가지 행동이 무엇일까?에 대한 고민이 많았는데 책에서 말하는 추상화 수준의 예시를 보니까 바로 이해가 되었다. 앞으로도 많이 활용하고자 한다. 그리고 아래 내용들도 많이 공감이 되었다.

- 함수 인자 (개인적으로 4개부터 많다고 생각한다)
- 명령과 조회 분리 
- 오류 코드보다 예외를 사용 
- 부수 효과를 읽으키지 마라

**Comment by ChanhuiSeok** [comment]
역시 코드의 시작은 **함수를 잘 작성하는 것**부터 시작한다고 생각이 든다.
어떤 프로젝트를 하더라도 함수는 반드시 작성하게 되어 있기 때문이다.

- 함수를 만드는 첫째 규칙은 ‘작게’ 이다. 둘째 규칙은 ‘더 작게’ 이다.
- 함수는 한 가지만 해야 한다. 그 한 가지를 잘 해야 한다.
- 함수에서 한 가지만 하겠다고 약속해놓고, 그 안에서 남몰래 다른 짓(부수 효과)을 하는 경우가 발생하면 안 된다.
ㄴ 💡 : 부수효과를 발생하지 말라는 이 내용은 정말 중요한 것 같다. 함수의 이름에서 보이는 역할과는 달리, 그 안에서 관련없는 어떤 내용을 수정하는 부분이 있다면, 나중에 다른 코드를 수정했을 때 문제가 터져도 찾기 어려울 수 있다. 실제로도 경험해 보았다. 매우 힘들었다.

- 함수의 파라미터는 0개가 인상적이다. 1개, 2개, ... 4개 이상은 특별한 이유가 필요하고, 이유가 있어도 사용하면 안 된다.
ㄴ 💡 : 요즘 IDE가 워낙 좋아서 함수 파라미터가 어떤 것인지 바로 뜨기는 하지만, 나도 인수가 쭉 여러 개로 많을 이유는 없다고 생각하고 예쁘지도 않다. 자바스크립트로 생각했을 때, 차라리 인수가 많아지면 파라미터를 객체로 하는 것이 좋다고 생각한다.
```js
// refineUserData함수는 어떠한 값을, 인자로 받는 데이터와 합쳐서 다시 반환하는 함수라고 가정한다.
function refineUserData(name, age, address) {...};
refineUserData('John', 20, '....');

// 수정 후. 그냥 userData라는 하나의 객체를 넘기면 나중에 호출부를 읽을 때 더 편하다.
function refineUserData(userData) { const {name, age, address} = userData; ... };
const userData = {name: ___, age: ___, address: ___};
refineUserData(userData);
```

- 파라미터가 너무 많아지면 인자값 순서를 실수로 잘못 넣을 수 있다.
ㄴ💡: 맞는 말이다. 그래서 이것은 자바스크립트에 대입해 보면, Parameter Destructuring으로 해결할 수 있다. 파라미터를 객체로 해놓고, 인자쪽에서 객체 프로퍼티를 어떤 순서로 하든 상관없이 구조 분해 할당으로 값을 받아올 수 있다.
```js
function refineUserData({name, age, address}) {...};
refineUserData({address: ___, age: ___, name: ___}); // 순서를 바꿔도 상관이 없다.

const userData = {name: ___, age: ___, address: ___};
refineUserData(userData); // 물론 이렇게 객체를 넘겨도 전혀 문제없다.
```

- Don’t Repeat Yourself → DRY 원칙! 반복하지 마라.
ㄴ 같은 알고리즘을 반복하지 말자. 중복되는 부분을 없애자.

- (정리) 논문이나 기사를 작성할 때 먼저 생각을 기록한 후 읽기 좋게 다듬는 것처럼, 함수를 짤 때도 처음에는 길고 복잡하고, 들여쓰기 단계도 많고, 중복된 루프도 많고, 인수 목록도 아주 길 수 있다. 하지만 이후 코드를 다듬고, 함수를 만들고, 이름을 바꾸고, 중복을 제거한다. (단위 테스트를 항상 통과하게 짜는 것은 덤)
ㄴ💡 : 맞다. 당연히 그렇게 할 수 밖에 없다. 처음부터 역할을 나누고, 깔끔하고 제대로 짰다고 생각해도 나중에 보면 무조건 1000% 흠이 보인다. 논문이나 기사를 작성하는 방법으로 비유한 것이 적절해 보였다.

**Comment by hhhyunwoo** [comment]
# ch03 Functions

Fitnesse 란

Fitnesse는 입력 값 과 결과 값을 WIKI페이지에 입력하고 검증을 수행하므로 항상 결과에 대한 기대 값은 동일해야 한다는 제약사항이 존재한다.

## Small!

1. 작아야함
2. 더 작아야함

스크린에 가득차면 안됨.

20줄정도

### Blocks and Indenting

if, while 등의 블록의 인덴트는 하나여야함. 즉, 중첩이면 안된다. 

## Do one Thing

Functions should do one thing. They should do it well, They should do it only

One thing 이라는 것을 판단하는 기준 - 추상화 레벨. 다른 이름으로 함수를 추출해낼 수 있다면 한가지 일이 아님

Keep It Simple Stupid

추상화 수준이 섞이면 특정 표현이 근본 개념인지, 세부사항인지 구분하기 어려움! 

## 내려가기 규칙

A

A’

B

B’

—

A

B

A’

B’

위의 내용이 더 맞다고 주장함.  스타일 차이?

## Switch 문

인스턴스를 생성만하는 factory 패턴으로는 가능! 

그렇지 않으면 case가 늘어날때마다 service logic의 switch문이 무한정 길어짐 

## 서술적인 이름 사용

## 함수 인수

무항이 이상적임

3,4개는 피하는게 좋음 

플래그 인수는 추함. → 플래그를 통해서 여러가지 작업을 하겠다는 것을 의미한다는 것이 모순

인수가 2,3개 필요하다면 클래스의 변수로 선언하는 것이 더 나음.


## 출력 인수

appendFooter(s);

s가 출력으로 사용되면 안됨! 좀 어색함

## 오류 코드보다 예외를 사용하라!

차라리 예외를 써라

근데 golang은

항상 이런식으로 err 를 리턴받을 수 있음.
