### ISSUE TITLE
[Ch04] Comments

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/cleancode-study#4]

**Comment by jjangsungwon** [comment]
`코드만이 자기가 하는 일을 진실되게 말한다.` 너무나 공감되는 말이다. 주석은 잘 쓰면 좋지만, 잘 쓰기가 참 힘든 것 같다. 코드는 오류를 뱉을 수 있지만 주석은 실행할 수 없기 때문이다.

그렇다면 언제 주석을 다는 게 좋을까?

- 의미를 명로하게 밝히는 주석
```java
// 테스트 코드를 읽을 때 아래처럼 주석이 있으면 해석하기 편했다.
assertTrue(a.compareTo(a) == 0); // a == a
assertTrue(a.compareTo(b) != 0); // a != b
```

- 결과를 경고하는 주석
  - 경험해 본 적은 없지만 충분히 의미 있는 주석이라고 생각한다.

나쁜 주석은 어떤 것일까? 대부분의 주석은 나쁜 주석이라고 생각한다.
- 같은 이야기를 중복하는 주석
- 오해할 여지가 있는 주석
- 이력을 기록하는 주석
  - 이전 회사에서 경험하였음. 이력을 기록한 주석의 길이가 100 줄 이상인 경우가 흔했음
  - 완전히 제거하는 게 좋다고 생각하지만 실천에 옮기기는 쉽지 않음. 따로 저장할 방법도 떠오르지 않았음.
- 닫는 괄호에 다는 주석
  - 괄호 위치 알려주는 플러그인을 사용하는 것이 좋다고 생각함
- 공로를 돌리거나 저자를 표시한 주석
  - 이전 회사에서 경험하였음. 코드 추가할 때마다 위에 저자 작성하였음. 공로보다는 책임을 전가하는 느낌이 강했음
- 주석으로 처리한 코드
  - 코드를 작성한 사람이 아니면 지우기도 애매함
 
결론
- 코드를 명확하게 작성하자. 그러면 주석은 줄어든다.
- 어떤 주석은 필요하거나 유익하다. 글자 값을 한다고 생각하는 주석은 최대한 활용하자!

**Comment by hhhyunwoo** [comment]
# Ch04 Annotation

### 주석은 필요악이다. 순수하게 선하지 못하다. 프로그래밍 언어로 치밀하게 의도를 표현할 수 있다면 주석은 거의 필요하지 않다.

- 프로그래머들이 주석을 유지하고 보수하기란 현실적으로 불가능하다.

근데 요새 잘 짜여진 거의 대부분의 오픈소스들은 엄청난 양의 주석을 가지고 있음.

근데 이게 코드에 대한 설명이라기 보다는 전체적인 오픈소스에 대한 설명이긴 하다 .
https://github.com/kubernetes/kubernetes/blob/4f74844299489e5edd2b1feda4476399dfced62d/pkg/controller/deployment/deployment_controller.go#L54-L100
```go
const (
	// maxRetries is the number of times a deployment will be retried before it is dropped out of the queue.
	// With the current rate-limiter in use (5ms*2^(maxRetries-1)) the following numbers represent the times
	// a deployment is going to be requeued:
	//
	// 5ms, 10ms, 20ms, 40ms, 80ms, 160ms, 320ms, 640ms, 1.3s, 2.6s, 5.1s, 10.2s, 20.4s, 41s, 82s
	maxRetries = 15
)

// controllerKind contains the schema.GroupVersionKind for this controller type.
var controllerKind = apps.SchemeGroupVersion.WithKind("Deployment")

// DeploymentController is responsible for synchronizing Deployment objects stored
// in the system with actual running replica sets and pods.
type DeploymentController struct {
	// rsControl is used for adopting/releasing replica sets.
	rsControl controller.RSControlInterface
	client    clientset.Interface

	eventBroadcaster record.EventBroadcaster
	eventRecorder    record.EventRecorder

	// To allow injection of syncDeployment for testing.
	syncHandler func(ctx context.Context, dKey string) error
	// used for unit testing
	enqueueDeployment func(deployment *apps.Deployment)

	// dLister can list/get deployments from the shared informer's store
	dLister appslisters.DeploymentLister
	// rsLister can list/get replica sets from the shared informer's store
	rsLister appslisters.ReplicaSetLister
	// podLister can list/get pods from the shared informer's store
	podLister corelisters.PodLister

	// dListerSynced returns true if the Deployment store has been synced at least once.
	// Added as a member to the struct to allow injection for testing.
	dListerSynced cache.InformerSynced
	// rsListerSynced returns true if the ReplicaSet store has been synced at least once.
	// Added as a member to the struct to allow injection for testing.
	rsListerSynced cache.InformerSynced
	// podListerSynced returns true if the pod store has been synced at least once.
	// Added as a member to the struct to allow injection for testing.
	podListerSynced cache.InformerSynced

	// Deployments that need to be synced
	queue workqueue.RateLimitingInterface
}
```

### 코드로 의도를 표현하라.

## 좋은 주석

- 법적인 주석
- 정보를 제공하는 주석
- 의도 설명 …

→ 주석이 올바른지 검증하기가  쉽지 않음.

- TODO 주석

## 나쁜 주석

- 거의 대부분
- 코드를 정당화하는 주석도 아니고, 의도나 근거를 설명하는 주석도 아니며, 코드보다 읽기 쉽지않음.
- 의무적인 주석
    - javadocs
    - python 도 있음.
- 있으나 마나 한 주석을 달려는 유혹에서 벗어나 코드를 정리해라
- 주석으로 처리한 코드는 매우 밉살스러운 관행
    - 소스코드 관리 시스템을 사용해야함
- 주석을 달아야 한다면 근처에 있는 코드만 기술해라

**Comment by ChanhuiSeok** [comment]
**주석에 대하여..**
- 나쁜 코드에 주석을 달지 말고 새로 짜라!
- 주석은 사실상 필요악이다.
- 주석이 코드에서 분리되어 부정확한 고아로 변하는 사례가 흔하다.
- 주석은 간혹 필요할지라도 줄이도록 꾸준히 노력해야 한다.
- 주석으로 달려는 설명을 함수로 만들어 표현해도 충분하다.

💡나의 경우,
어떤 한 개의 값을 구하는데, 두 개의 분리된 함수를 순차적으로 사용하고 있었고, 각각의 함수에 주석을 달아두는 형태로 구현했었다. 최근 리팩토링을 진행했는데, 두 함수를 하나의 함수로 합치고, 주석을 아예 없앴더니 더 명확히 이해가 가는 함수로 바뀌었다.

**좋은 주석**
- 법적인 주석은 필요하고도 타당하다. (저작권 정보, 소유권 정보)
- 의도를 설명하는 주석. 구현을 이해하게 도와주는 선을 넘어 결정에 깔린 의도까지 설명하는 주석이 있다. 💡적어두면 이해에는 도움이 될 것 같다.
- TODO 주석 💡프로젝트에서 꽤 많이 사용하고 있다. 최근에는 예전에 스프린트를 진행할 당시 TODO로 남겨두었던 주석들을 모두 해결하는 PR을 올리기도 했다.

**나쁜 주석**

- **주절거리는 주석.** 💡이해가 안 되어 다른 모듈까지 뒤져야 하는 주석은 독자와 제대로 소통하지 못하는 주석이다. → 어느정도 공감이 된다. 주석을 읽지만 잘 이해가 안 갈때 그런 느낌을 받았다.

- **같은 이야기를 중복하는 주석.** 💡그리고 tomcat에 쓸모 없는 Javadocs가 매우 많다고 이야기하고 있다. 유명한 오픈소스에도 이런 지적받을 사항이 분명 있구나 하는 점을 깨닫는다.

- **오해할 여지가 있는 주석.** 💡이건 당연히 피해야 하겠다. 주석을 안 다느니만 못하다.

- **의무적으로 다는 주석.** 💡여기에 나오는 예시에 Javadocs로 넣은 주석의 예시가 나온다. 그리고는 Javadocs를 넣으라는 의무적인 규칙이 낳은 괴물이라고 한다.(Javadocs가 굳이 필요없는 상황에서도 쓰는 경우)
자바스크립트에서도 이와 비슷한 jsdocs라고 유사한 형태로 주석을 다는 경우가 있다. 의미 없이 함수 인자에 대해서만 주석을 나열할거면 jsdocs는 안쓰는 것이 좋겠다. 그러한 유형의 주석은 문서화할 것이 아니면 타입스크립트를 많이 쓰는 요즘에는 더욱 필요없다고 생각한다.

- **이력을 기록하는 주석.** 💡 소스코드 수정에 대한 이력은 git이 있으니까 이러한 주석은 완전히 제거하는 편이 좋겠다.

- **공로를 돌리거나 저자를 표시하는 주석을 달지 말자.** 💡 누가 언제 추가했는지는 git과 같은 소스 코드 관리 시스템이 너무나 잘 알려 준다.

- **주석으로 처리한 코드를 저장하지 말자.**
- **주석에 너무 많은 정보를 담지 말자. 흥미로운 역사나 관련 없는 정보를 장황하게 늘어놓지 말자.**
- **공개 API는 Javadocs가 유용하겠지만, 공개하지 않을 코드라면 쓸모가 없다.** 💡 간혹 가다 jsdocs을 쓴 코드를 보았는데, 사실상 정말 필요한 것인지 잘 생각해봐야 한다.
