### ISSUE TITLE
[Ch08] Boundaries

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/cleancode-study#8]

**Comment by hhhyunwoo** [comment]
## 외부 코드 사용하기

- 오픈소스가 매우 매우 대중화 된 지금 오픈소스 사용은 거의 불가피함
    - 거의 대부분의 기능을 가진 것들이 오픈소스화 되어 있기 때문에 요즘은 먼저 구현하기 보다 구글링을 먼저함

### 경계 살피고 익히기

- 오픈소스를 사용할 때 곧바로 우리 코드에서 외부 코드를 호출하기 보단, 외부 코드에 대한 테스트 케이스 작성 및 익히는 방법도 괜찮음
    - 학습 테스트
    - 더 빠르게 익힐 수 있고, 독자적인 클래스로 캡슐화할 수 있음
    - 학습 테스트는 공짜 이상이고, 노력보다 얻는 성과가 더 큼
- 테스트 케이스 필요!
- 코드를 불러오는 경우가 아니라 컴포넌트 자체를 가져와서 우리 플랫폼에 붙이는 작업을 했었는데, 해당 외부 플랫폼에 대한 이해도를 쌓는 행위가 선행되는 것이 매우 중요했음

### 아직 존재하지 않는 코드를 사용하기

- 아는 코드와 모르는 코드를 분리하는 경계
- 인터페이스 정의
- ADAPTER 패턴
    - 
    
    ![image](https://user-images.githubusercontent.com/37402136/184395500-e9b2bb6b-0272-49ac-a762-deff1e806588.png)
    
    - 전기 콘센트
        - 한국 표준 플러그를 일본 전원 소켓이 끼우기 위해서는 어댑터를 끼워야함.
        - 어댑터는 소캣의 인터페이스를 플러그에서 필요로 하는 인터페이스로 바꿔줌
    - → 현재 사용하고 있는 라이브러리가 더 이상 요구에 부합하지 않아 재작성하거나, 다른 라이브러리를 사용해야할 때가 있음. adapter 패턴을 이용하면 기존 코드를 가능한 적게 변경하면서 교체할 수 있다.

**Comment by jjangsungwon** [comment]
**기억에 남은 문구**
- 패키지 제공자나 프레임워크 제공자는 적용성을 최대한 넓히려 애쓴다. 반면, 사용자는 자신의 요구에 집중하는 인터페이스를 바란다. 이런 긴장으로 인해 시스템 경계에서 문제가 생길 소지가 많다.
- 우리가 바라는 인터페이스를 구현하면 우리가 인터페이스를 전적으로 통제한다는 장점이 생긴다.
- 통제가 불가능한 외부 패키지에 의존하는 대신 통제가 가능한 우리 코드에 의존하는 편이 훨씬 좋다. 자칫하면 오히려 외부 코드에 휘둘리고 만다.

**학습 테스트**
- 프로그램에서 사용하려는 방식대로 외부 API를 호출한다.
  - 지금까지는 외부 API 따로 호출해서 동작 확인하고 프로그램에 넣으려고 했었다. 앞으로는 학습 테스트 방식을 활용해야겠다.

**ADAPTER 패턴**
- 클래스의 인터페이스를 사용자가 기대하는 인터페이스 형태로 적응(변환) 시킨다. 서로 일치하지 않는 인터페이스를 갖는 클래스들을 함께 동작시킨다.
- API가 바뀔 때 수정할 코드를 한곳으로 모았다.

**Comment by ChanhuiSeok** [comment]
외부 패키지를 호출하는 코드를 가능한 줄여 경계를 관리하자.
이번 8장은 **외부 코드와 우리 코드에 통합할 때 경계라는 관점**을 새롭게 배울 수 있었다.

- `학습 테스트` -> 외부 코드를 익히거나 통합하기 어려우면, 다르게 접근하자. **곧바로 우리쪽 코드를 작성해 외부 코드를 호출하는 대신, 먼저 간단한 테스트 케이스를 작성해서 외부 코드를 익히는 방식이 좋다.** 학습 테스트는 우리 코드와 잘 호환되는지, 패키지가 예상대로 도는지 검증할 수 있다.

- 어댑터 패턴 -> 어댑터는 호환되지 않는 인터페이스를 함께 동작할 수 있도록 변환시킨다. (110v <-> 220v 변환 어댑터 같은 개념)

- 소프트웨어 설계까 우수하다면 변경하는데 많은 투자와 재작업이 필요하지 않다. 통제하지 못하는 코드를 사용하면 너무 많은 투자를 하거나 향후 변경 비용이 지나치게 커지지 않게 각별히 주의해야 한다. ✏ 이건 앞서 OCP 이야기와 이어질 수 있는 내용이라고 본다.
