### ISSUE TITLE
[Ch09] Unit Tests

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/cleancode-study#9]

**Comment by hhhyunwoo** [comment]
테스트 코드가 중요하다고 듣고 가끔 생각하기만 했지 이렇게 강조되는 부분일 줄은 몰랐다.

TDD에 대해서 부정적으로 보는 사람들도 있어서 그렇구나 하고 생각했었는데 클린코드의 철학에서는 TDD가 필수인 것 처럼 보인다!

## TDD 법칙

1. 실패하는 테스트를 작성할 때까지 코드 작성 X
2. 컴파일은 실패하지 않으면서 실행이 실패하는 정도로만 테스트 작성
3. 현재 실패하는 테스트를 통과할 정도만으로 실제 코드 작성

→ 개발 테스트 주기가 30초 정도

대애박 

## 테스트 코드는 실제 코드 못지 않게 중요함!

- 실제 코드가 진화하면 테스트 코드도 변화해야한다.
- 테스트 코드를 깨끗하게 유지하지 않으면 결국을 잃어버림
- 테스트 코드를 잘 짜두면 변경이 쉬워지고 변화를 통해 발생하는 버그에 대한 공포가 사라짐
- 가독성, 가독성, 가독성! 이 중요함

### Build- Operate- Check 패턴

1. 테스트 자료 만들기
2. 테스트 자료 조작
3. 조작한 결과가 올바른지 확인

## 좋은 테스트 규칙

- 개념 당 assert 문 수를 최소로 줄여라
    - 무조건 1개일 때는 중복 코드가 많아지고, 부모 클래스 적용으로 해결할 수 있긴 하지만,, 굳이 1개를 고집할 필요는 없음. 하지만 최소로 줄이려고 노력은 해야함!
- 테스트 함수 하나는 개념 하나만 테스트하라

## Fast, Independent, Repeatable, Self-Validating, Timely

- 실제 코드 구현 직전에, bool(성공, 실패) 결과를 내며 어떠한 환경에서도 반복 가능 해야 하고 빠르고 의존성이 없이 작성해야함!

## TDD 매우 중요! 나중에 다시 깊게 공부해볼 필요 있음!

근데 왜 애자일에서 TDD를 쓸까?

→ 추상적인 레벨에서의 TDD의 핵심 개념

- 결정과 피드백 사이의 갭에 대한 인식, → 결정과 피드백 사이의 갭을 조절하기 위한 테크닉
- 즉, 애자일의 철학을 도입한 프로그래밍 기법이 TDD아닐까?
- 만약 어떤 부분에 대한 코딩을 여러번 해봤고, 결과를 예측할 수 있다면 TDD를 하지 않아도 됨!
- 처음하는 주제, 불확실성이 있거나 요구조건이 바뀔 수 있을 때!  TDD를 진행함
    - 즉, 애자일이 적용되는 플젝에는 TDD가 적합할 가능성이 매우 농후!

**Comment by ChanhuiSeok** [comment]
테스트 코드의 중요성은 실제 프로젝트에서도 경험하고 있다. 안심하고 코드를 수정할 수 있는 환경을 제공한다. 그리고 실제로도 도움을 많이 받고 있다.

- `테스트 코드는 지저분하면 안 된다.`
✏️ 복잡할수록 실제 코드를 짜는 시간보다 더 걸린다. 테스트 코드는 실제 코드 못지 않게 중요하다. 깨끗하게 짜야 한다.
- `테스트 케이스가 있다면 공포는 사실상 사라진다.` 
✏️ 매우 매우 공감한다. 내가 하는 프로젝트도 테스트 케이스가 잘 갖추어져 있다. 각종 사이드 이펙트를 처리하는 로직이 얽혀 있더라도 명확한 테스트 항목들이 있기 때문에 안심하고 코딩하고, 수정할 수 있다고 생각한다.
- `깨끗한 테스트 코드를 만들려면 가독성이 정말 중요하다.`
✏️ JavaScript 에서는 jest 라는 테스트 프레임워크를 많이 쓰고 있다. jest로 테스트 코드를 작성할 때도 가독성 고민을 많이 했던 것 같다.
- `테스트 당 assert 문 하나를 유지하는 게 좋다.` 
✏️ aseert문은 JUnit에서 테스트 결과를 확인하는 메서드이다. 테스트 하나 당, 결과 한 번 확인이면 이해하기 쉽다는 측면을 책에서 말하는 것 같다.
- `테스트 당 개념 하나` → 테스트 함수마다 하나의 개념만 테스트하자.
- `깨끗한 테스트가 따르는 다섯 가지 규칙` → F.I.R.S.T
    - 테스트는 빨라야 한다. 느리면 자주 돌릴 엄두를 못 낸다. ✏️ 빠르면 당연히 좋겠다. 만약 실제 프로덕션으로 나갈 서비스의 경우 테스트 코드가 조금 느려졌더라도 반드시 거쳐야 한다고 생각한다.
    - 각 테스트는 서로 의존하면 안 된다.
    - 반복 가능해야 한다. 테스트는 어떤 환경에서도 잘 돌아가야 한다.
    - 테스트는 부울 값으로 결과를 내야 한다. 즉, **성공 아니면 실패이다.**
    - 적시에 작성해야 한다. 단위 테스트는 테스트하려는 실제 코드를 구현하기 직전에 구현한다. ✏️ 아직까지는 실제 코드를 작성하고, 테스트 코드를 나중에 작성하는 방식으로 더 많이 진행했던 것 같다. 실제 코드보다 테스트를 미리 작성한다면 그 코드가 어떻게 돌아가야 하는지 전체적인 그림을 그릴 수 있어서 더 도움이 되는 것일까? 이 부분은 직접 해보고 비교해야겠다.
- `테스트 코드는 실제 코드만큼이나 프로젝트 건강에 중요하다.`
✏️ 푸시할 때마다 테스트 코드 검사 단계를 거치고 있는데, 코드를 수정했을 때 미처 생각하지 못한 것들을 테스트 코드에서 다 잡아주니까 정말 도움이 많이 된다.

**Comment by jjangsungwon** [comment]
### TDD 법칙 세 가지
  - 첫쨰 법칙 : 실패하는 단위 테스트를 작성할 때까지 실제 코드를 작성하지 않는다.
  - 둘째 법칙 : 컴파일은 실패하지 않으면서 실행이 실패하는 정도로만 단위 테스트를 작성한다.
  - 셋째 법칙 : 현재 실패하는 테스트를 통과할 정도로만 실제 코드를 작성한다.
  - 실제 코드를 사실상 전부 테스트하는 테스트 케이스가 나온다.

하지만, 테스트 코드가 실제 코드보다 불과 몇 초 전에 나오는 건 공감이 안됨. 둘 사이에 간격이 생각보다 길었음.

### 깨끗한 테스트 코드 유지하기
- 실제 코드가 진화하면 테스트 코드도 변해야 한다는 데 있다.
- 실제 코드를 변경해 기존 테스트 케이스가 실패하기 시작하면, 지저분한 코드로 인해, 실패하는 테스트 케이스를 점점 더 통과시키기 어려워진다.
- 테스트 코드는 실제 코드 못지 않게 깨끗하게 짜야 한다.
- 테스트는 유연성, 유지보수성, 재사용성을 제공한다.
- 가독성이 중요하다.

실제 코드만큼 효율적일 필요는 없다. 실제 환경이 아니라 테스트 환경에서 돌아가는 코드이기 때문이다.
- 실제와 최대한 환경이 유사해야한다고 생각한다. 테스트 환경에서 돌아가는게 중요한게 아니라 실제 환경에서 돌아가는게 중요하기 때문이다. 현재 진행하고 있는 프로젝트도 모두 실제와 동일한 환경에서 테스트 코드를 수행하고 있다. 

### F.I.R.S.T
- 빠르게, 독립적으로, 반복가능하게, 자가검증하는, 적시에
